"""
Chrome 쿠키 자동 추출 유틸리티
"""

import os
import sqlite3
import json
from pathlib import Path
from typing import Optional

def get_chrome_cookie_path():
    """Chrome 쿠키 DB 경로 찾기 (Windows)"""
    # Windows Chrome 기본 경로
    user_data_path = Path.home() / "AppData" / "Local" / "Google" / "Chrome" / "User Data"
    
    # Default 프로필 쿠키 경로
    cookie_path = user_data_path / "Default" / "Network" / "Cookies"
    
    if cookie_path.exists():
        return cookie_path
    
    # Profile 1, 2, 3... 확인
    for i in range(1, 10):
        profile_cookie_path = user_data_path / f"Profile {i}" / "Network" / "Cookies"
        if profile_cookie_path.exists():
            return profile_cookie_path
    
    return None

def extract_youtube_cookies() -> Optional[str]:
    """
    Chrome에서 YouTube 쿠키 자동 추출
    
    Returns:
        Netscape format 쿠키 문자열 또는 None
    """
    cookie_db_path = get_chrome_cookie_path()
    
    if not cookie_db_path:
        return None
    
    # 임시 복사본 생성 (Chrome이 DB를 잠그고 있을 수 있음)
    import shutil
    import tempfile
    
    temp_db = os.path.join(tempfile.gettempdir(), 'chrome_cookies_copy.db')
    
    try:
        shutil.copy2(cookie_db_path, temp_db)
    except Exception as e:
        print(f"쿠키 DB 복사 실패: {e}")
        return None
    
    try:
        # SQLite 연결
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()
        
        # YouTube 쿠키 조회
        cursor.execute("""
            SELECT host_key, name, value, path, expires_utc, is_secure, is_httponly
            FROM cookies
            WHERE host_key LIKE '%youtube.com%'
        """)
        
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            return None
        
        # Netscape format으로 변환
        cookies_txt = "# Netscape HTTP Cookie File\n"
        cookies_txt += "# This file was generated by Bes2 Marketer\n\n"
        
        for row in rows:
            host_key, name, value, path, expires_utc, is_secure, is_httponly = row
            
            # Netscape format
            # domain, flag, path, secure, expiration, name, value
            domain_flag = "TRUE" if host_key.startswith('.') else "FALSE"
            secure_flag = "TRUE" if is_secure else "FALSE"
            
            # expires_utc는 Chrome epoch (microseconds since 1601-01-01)
            # Unix epoch로 변환 (seconds since 1970-01-01)
            if expires_utc:
                # Chrome epoch base: 1601-01-01
                # Unix epoch base: 1970-01-01
                # Difference: 11644473600 seconds
                unix_timestamp = (expires_utc / 1000000) - 11644473600
                expiration = int(unix_timestamp)
            else:
                expiration = 0
            
            cookies_txt += f"{host_key}\t{domain_flag}\t{path}\t{secure_flag}\t{expiration}\t{name}\t{value}\n"
        
        return cookies_txt
        
    except Exception as e:
        print(f"쿠키 추출 중 오류: {e}")
        return None
    finally:
        # 임시 파일 삭제
        try:
            os.remove(temp_db)
        except:
            pass

def save_cookies_to_file(cookies_txt: str, output_path: str) -> bool:
    """쿠키를 파일로 저장"""
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(cookies_txt)
        return True
    except Exception as e:
        print(f"쿠키 저장 실패: {e}")
        return False

if __name__ == "__main__":
    # 테스트
    cookies = extract_youtube_cookies()
    if cookies:
        print("✅ 쿠키 추출 성공!")
        print(f"쿠키 개수: {len(cookies.splitlines())}줄")
        
        # 저장
        output_path = os.path.join(os.path.dirname(__file__), 'cookies.txt')
        if save_cookies_to_file(cookies, output_path):
            print(f"✅ 쿠키 저장 완료: {output_path}")
        else:
            print("❌ 쿠키 저장 실패")
    else:
        print("❌ 쿠키 추출 실패")
